module.exports = {
    'parser': 'babel-eslint',
    'parserOptions': {
        'ecmaVersion': 6,
        'sourceType': 'module',
        'ecmaFeatures': {
            'jsx': true,
            'experimentalObjectRestSpread': true
        }
    },
    'env': {
        'browser': true,
        'node': true
    },
    'rules': {
        'comma-dangle': [2, 'never'],
        'no-cond-assign': [2, 'always'],
        'no-console': [1],
        'no-constant-condition': [2],
        'no-control-regex': [2],
        'no-debugger': [1],
        'no-dupe-args': [2],
        'no-dupe-keys': [2],
        'no-duplicate-case': [2],
        'no-empty': [2],
        'no-empty-character-class': [2],
        'no-ex-assign': [2],
        'no-extra-parens': [2],
        'no-extra-semi': [2],
        'no-func-assign': [2],
        'no-inner-declarations': [2, 'both'],
        'no-invalid-regexp': [2],
        'no-irregular-whitespace': [2],
        'no-negated-in-lhs': [2],
        'no-obj-calls': [2],
        'no-regex-spaces': [2],
        'no-sparse-arrays': [2],
        'no-unexpected-multiline': [2],
        'no-unreachable': [2],
        'no-unsafe-finally': [2],
        'use-isnan': [2],
        'valid-typeof': [2],
        'accessor-pairs': [2],
        'array-callback-return': [2],
        'block-scoped-var': [1],
        'consistent-return': [2],
        'curly': [2, 'all'],
        'default-case': [2],
        'dot-location': [2, 'property'],
        'dot-notation': [2],
        'eqeqeq': [2, 'allow-null'],
        'no-alert': [2],
        'no-caller': [2],
        'no-case-declarations': [2],
        'no-empty-function': [2],
        'no-empty-pattern': [2],
        'no-eval': [2],
        'no-extend-native': [2],
        'no-extra-bind': [2],
        'no-extra-label': [2],
        'no-fallthrough': [2],
        'no-floating-decimal': [2],
        'no-implicit-coercion': [2],
        'no-implied-eval': [2],
        'no-iterator': [2],
        'no-labels': [2],
        'no-lone-blocks': [2],
        'no-loop-func': [2],
        'no-multi-spaces': [2],
        'no-native-reassign': [2],
        'no-new': [2],
        'no-new-func': [2],
        'no-new-wrappers': [2],
        'no-octal': [2],
        'no-octal-escape': [2],
        'no-param-reassign': [2, {'props': true}],
        'no-proto': [2],
        'no-redeclare': [2, {'builtinGlobals': true}],
        'no-return-assign': [2, 'always'],
        'no-script-url': [2],
        'no-self-assign': [2],
        'no-self-compare': [2],
        'no-sequences': [2],
        'no-throw-literal': [2],
        'no-unmodified-loop-condition': [2],
        'no-unused-expressions': [2],
        'no-void': [2],
        'no-warning-comments': [1],
        'no-with': [2],
        'radix': [2, 'always'],
        'wrap-iife': [2, 'inside'],
        'yoda': [2, 'never'],
        'init-declarations': [2, 'always'],
        'no-delete-var': [2],
        'no-restricted-globals': [2, 'event'],
        'no-shadow-restricted-names': [2],
        'no-undef': [2],
        'no-unused-vars': [2],
        'no-use-before-define': [2],
        'array-bracket-spacing': [2, 'never'],
        'block-spacing': [2, 'always'],
        'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
        'camelcase': [2],
        'comma-spacing': [2, {'before': false, 'after': true}],
        'comma-style': [2, 'last'],
        'computed-property-spacing': [2, 'never'],
        'consistent-this': [2, 'self'],
        'indent': [2, 4, {'SwitchCase': 1}],
        'jsx-quotes': [2, 'prefer-single'],
        'key-spacing': [2, {'beforeColon': false, 'afterColon': true}],
        'keyword-spacing': [2, {'before': true, 'after': true}],
        'lines-around-comment': [2, {'beforeBlockComment': true}],
        'max-len': [2, {'code': 120, 'ignoreUrls': true}],
        'new-cap': [2, {'capIsNew': false}],
        'new-parens': [2],
        'newline-after-var': [2, 'always'],
        'no-continue': [2],
        'no-lonely-if': [2],
        'no-multiple-empty-lines': [2, {'max': 1, 'maxBOF': 0}],
        'no-nested-ternary': [2],
        'no-new-object': [2],
        'no-spaced-func': [2],
        'no-trailing-spaces': [2],
        'no-unneeded-ternary': [2],
        'no-whitespace-before-property': [2],
        'object-curly-spacing': [2, 'never'],
        'operator-linebreak': [2, 'after'],
        'quote-props': [2, 'as-needed'],
        'quotes': [2, 'single', {'allowTemplateLiterals': true}],
        'semi': [2, 'always'],
        'semi-spacing': [2, {'before': false, 'after': true}],
        'space-before-blocks': [2, 'always'],
        'space-before-function-paren': [2, {'anonymous': 'always', 'named': 'never'}],
        'space-in-parens': [2, 'never'],
        'space-infix-ops': [2],
        'spaced-comment': [2, 'always'],
        'arrow-body-style': [2, 'as-needed'],
        'arrow-parens': [2, 'as-needed'],
        'arrow-spacing': [2, {'before': true, 'after': true}],
        'constructor-super': [2],
        'generator-star-spacing': [2, 'before'],
        'no-class-assign': [2],
        'no-const-assign': [2],
        'no-dupe-class-members': [2],
        'no-duplicate-imports': [2],
        'no-new-symbol': [2],
        'no-useless-computed-key': [2],
        'no-useless-constructor': [2],
        'no-var': [2],
        'prefer-const': [2],
        'prefer-rest-params': [2],
        'prefer-spread': [2],
        'template-curly-spacing': [2, 'never'],
        'yield-star-spacing': [2, 'before']
    }
};
